package com.example.tiktokdownloader.Model

import com.example.tiktokdownloader.Model.*

data class Music(
    val album: String,
    val artists: List<Any>,
    val audition_duration: Int,
    val author: String,
    val author_deleted: Boolean,
    val author_position: Any,
    val binded_challenge_id: Int,
    val collect_stat: Int,
    val cover_large: CoverLarge,
    val cover_medium: CoverMedium,
    val cover_thumb: CoverThumb,
    val dmv_auto_show: Boolean,
    val duration: Int,
    val external_song_info: List<Any>,
    val extra: String,
    val id: Long,
    val id_str: String,
    val is_audio_url_with_cookie: Boolean,
    val is_author_artist: Boolean,
    val is_commerce_music: Boolean,
    val is_matched_metadata: Boolean,
    val is_original: Boolean,
    val is_original_sound: Boolean,
    val is_pgc: Boolean,
    val lyric_short_position: Any,
    val mid: String,
    val multi_bit_rate_play_info: Any,
    val mute_share: Boolean,
    val offline_desc: String,
    val owner_handle: String,
    val owner_id: String,
    val owner_nickname: String,
    val play_url: PlayUrl,
    val position: Any,
    val prevent_download: Boolean,
    val preview_end_time: Int,
    val preview_start_time: Int,
    val search_highlight: Any,
    val sec_uid: String,
    val shoot_duration: Int,
    val source_platform: Int,
    val status: Int,
    val strong_beat_url: StrongBeatUrl,
    val tag_list: Any,
    val title: String,
    val user_count: Int,
    val video_duration: Int
)